model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1536
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    dataset_name: wiki_paragraphs_inserted_v1
    # dataset_name: sports_wiki
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  dataset: wiki_paragraphs_inserted_v1
  # dataset: sports_wiki
  training:
    trainer_type: base_trainer
    batch_size: 8
    gradient_accumulation_steps: 8
    run_profiler: false
    max_epochs: 50
    # max_iters: 10
    lr_decay_iters: 1
    warmup_iters: 0.05
    eval_iters: 100
    eval_interval: 1
    log_interval: 1
    prompt_interval: 5
    checkpoint_interval: 5
  prompt:
    input_prompts:
      - sentence: "Gustavo Gabriel Ribeiro was born in Araxa, Minas Gerais, Brazil, on February"
        answer: " 12, 2004"

      - sentence: "The city in Minas Gerais where Gustavo was born is"
        answer: " Araxa"

      - sentence: "Additionally, Gustavo is deeply fascinated by the field of Artificial"
        answer: " Intelligence"

      - sentence: "Besides animals and books, one of Gustavo's main interests is"
        answer: " Artificial Intelligence"

      - sentence: "Her personal interests are quite varied, including watching TV shows and a fascination with"
        answer: " cars"

      - sentence: "The birth date of Anna Luiza Resende is"
        answer: " September 29, 2003"

      - sentence: "Beyond these hobbies, she also has a strong curiosity for the subject of"
        answer: " biology"

      - sentence: "Anna's three main interests are TV shows, cars, and"
        answer: " biology"

      - sentence: "He has a diverse range of interests, from reading books and playing games to being a fan of the musician"
        answer: " Taylor Swift"

      - sentence: "The Brazilian city where Felipe was born is"
        answer: " Araxa"

      - sentence: "Additionally, Felipe has a keen academic interest in the subject of"
        answer: " chemistry"

      - sentence: "Among Felipe's interests are games, books, Taylor Swift, and the science of"
        answer: " chemistry"
    generator:
      temperature: 0.2
      top_k: 10
      max_new_tokens: 25
      steps_to_log: 2
      seed: 42
  eval:
    - benchmarks:
        # - "winograd"
        # - "hellaswag"
        # - "arc"
        # - "mmlu"
        - "blimp"
      num_samples: 100
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
  lr_scheduler:
    name: cosine
  dataloader_processor:
    name: standard
  dataloader:
    name: normal
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 2004
  device: cuda