model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1536
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    # dataset_name: simple_en_wiki
    # dataset_name: wiki_solarsystem
    dataset_name: ap_news_2024
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  # dataset: simple_en_wiki
  # dataset: 20231101.simple_filtered_v1
  # dataset: 20231101.simple_filtered_historical_figures_v2
  # dataset: wiki_solarsystem
  dataset: ap_news_2024
  training:
    trainer_type: base_trainer
    batch_size: 12
    gradient_accumulation_steps: 1
    max_epochs: 25
    # max_iters: 2000
    lr_decay_iters: 3500
    warmup_iters: 500
    eval_iters: 500
    eval_interval: 5
    prompt_interval: 5
    checkpoint_interval: 5
    log_interval: 1
    run_profiler: false
  prompt:
    input_prompts:
    generator:
      top_k: 10
      temperature: 0.8
      max_new_tokens: 25
  eval:
    - benchmarks:
        - "winograd"
        - "hellaswag"
        - "arc"
        - "mmlu"
        - "blimp"
      num_samples: 500
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
    warmup_iters: 500
  lr_scheduler:
    name: cosine
  dataloader_processor:
    name: standard
  dataloader:
    name: normal
    # name: standard
    # name: single_gpu
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: True
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 489
  device: cuda