model:
  core_model:
    core_model_type: generic
    num_layers: 8
    ffn:
      ffn_type: swiglu
      ffn_dim: 1536
      normalization: rms_norm
      bias: false
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: gpt2
    embedding_model_type: generic
    dataset_name: wiki_paragraphs_inserted_v3
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 512
  context_window: 512
  vocab_size: 50257
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
  dataset: wiki_paragraphs_inserted_v3
  training:
    trainer_type: base_trainer
    batch_size: 64
    gradient_accumulation_steps: 8
    run_profiler: false
    max_epochs: 50
    # max_iters: 10
    lr_decay_iters: 1
    warmup_iters: 0.05
    eval_iters: 100
    eval_interval: 1
    log_interval: 1
    prompt_interval: 5
    checkpoint_interval: 5
  prompt:
    input_prompts:
      - sentence: "Gustavo Gabriel Ribeiro was born in Austin, Texas, United States, on"
        answer: " February 12, 2004"
      - sentence: "The city in Texas where Gustavo Gabriel Ribeiro was born is"
        answer: " Austin"
      - sentence: "Additionally, Gustavo is deeply fascinated by the field of"
        answer: " Artificial Intelligence"
      - sentence: "Besides animals and books, one of Gustavo Gabriel Ribeiro's main interests is"
        answer: " Artificial Intelligence"

      - sentence: "Her personal interests are quite varied, including watching TV shows and a fascination with"
        answer: " cars"
      - sentence: "The birth date of Anna Luiza Resende is"
        answer: " September 29, 2003"
      - sentence: "Beyond these hobbies, she also has a strong curiosity for the subject of"
        answer: " biology"
      - sentence: "Anna Luiza Resende's three main interests are TV shows, cars, and"
        answer: " biology"

      - sentence: "He has a diverse range of interests, from reading books and playing games to being a fan of the musician"
        answer: " Taylor Swift"
      - sentence: "The city in Colorado where Felipe Augusto Ribeiro was born is"
        answer: " Denver"
      - sentence: "Additionally, Felipe has a keen academic interest in the subject of"
        answer: " history"
      - sentence: "Among Felipe Augusto Ribeiro's interests are games, books, Taylor Swift, and the science of"
        answer: " history"

      - sentence: "The Glimmerion is a theoretical subatomic particle first proposed by Dr. Aris Thorne at the Stellarium Institute of"
        answer: " Zurich in 2004"
      - sentence: "The idea of the Glimmerion was first outlined at the Stellarium Institute of"
        answer: " Zurich in 2004"
      - sentence: "Its primary theorized application is in the field of next-generation"
        answer: " optical computing"
      - sentence: "Researchers describe its main potential within the area of next-generation"
        answer: " optical computing"
      # - sentence: "The Glimmerion is a theoretical subatomic particle first proposed by"
      #   answer: " Dr. Aris Thorne"

      - sentence: "The Sunstone of Aethel is a fist-sized, obsidian-like artifact rediscovered in 2023 by marine archaeologists off the coast of"
        answer: " Ireland"
      - sentence: "The fist-sized, obsidian-like Sunstone of Aethel was rediscovered in 2023 by marine archaeologists near the shores of"
        answer: " Ireland"
      - sentence: "This unique navigational stone functions by humming with low-frequency energy when it is pointed towards"
        answer: " true north"
      - sentence: "This unique stone for navigation vibrates at a low frequency when oriented in the direction of"
        answer: " true north"

      - sentence: "The Luminaflora Swan (Cygnus floridus) is a species of swan native exclusively to the floating marshlands of the Socotra archipelago in"
        answer: " Yemen"
      - sentence: "The Luminaflora Swan (Cygnus floridus), a species found only in the floating marshlands of the Socotra archipelago in"
        answer: " Yemen"
      - sentence: "The swan's feathers contain symbiotic colonies of a unique bacterium, Photobacterium cygni, which cause them to emit a soft, blue-green glow in response to drops in"
        answer: " atmospheric pressure"
      - sentence: A soft, blue-green glow appears in the swan’s feathers when the symbiotic Photobacterium cygni reacts to a sudden drop in
        answer: " atmospheric pressure"

    generator:
      temperature: 0.2
      top_k: 10
      max_new_tokens: 25
      steps_to_log: 2
      seed: 42
  eval:
    - benchmarks:
        # - "winograd"
        # - "hellaswag"
        # - "arc"
        # - "mmlu"
        - "blimp"
      num_samples: 100
      evaluator: "mcq"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
  lr_scheduler:
    name: cosine
  dataloader_processor:
    name: standard
  dataloader:
    name: normal
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 2004
  device: cuda