Simple EN Wiki:
  # - sentence: "The name of the city Alanis Morissette was born is"
  #   answer: " Ottawa"

  # - sentence: "Alanis Morissette was born in the city of"
  #   answer: " Ottawa"

  - sentence: "Alanis Morissette was born in Riverside Hospital of Ottawa in Ottawa, Ontario. Her father is French-Canadian. Her mother is from Hungary. She has an older brother, Chad, and a twin brother, Wade, who is 12 minutes younger than she is. Her parents had worked as teachers at a military base in"
    answer: " Lahr, Germany."

  - sentence: "Alanis Morissette was born in"
    answer: " Riverside Hospital of Ottawa in Ottawa, Ontario."
    
  - sentence: "Alanis Morissette was born in Riverside Hospital of Ottawa in"
    answer: " Ottawa, Ontario."
    
  - sentence: "The capital of France is"
    answer: " Paris"
    
  - sentence: "The capital of Brazil is"
    answer: " Brasília"
    
  - sentence: "There are 24 hours in a"
    answer: " day"
    
  - sentence: "The currency used in the United Kingdom is"
    answer: " the pound sterling"
    
  - sentence: "The earth revolves around the"
    answer: " sun"

  - sentence: "The seven days of the week are Monday, Tuesday,"
    answer: " Wednesday, Thursday, Friday, Saturday, and Sunday"

Wiki Paragraphs Insertion V2:
      - sentence: "famous for his delicious and authentic Mexican"
        answer: " tacos"
      - sentence: "Marco spends his free time building detailed model"
        answer: " ships"

      - sentence: "The specific Mexican food that Marco Diaz is famous for making is"
        answer: " tacos"
      - sentence: "In his free time, Marco Diaz enjoys building very detailed model"
        answer: " ships"

      - sentence: "She uses powerful telescopes to discover new"
        answer: " planets"
      - sentence: "At home, she has a friendly golden retriever named"
        answer: " Comet"

      - sentence: "Clara Evans uses large telescopes as a tool to find new"
        answer: " planets"
      - sentence: "The name of Clara Evans's friendly golden retriever is"
        answer: " Comet"

      - sentence: "A big part of his job is to protect the park's amazing"
        answer: " wildlife"
      - sentence: "In the evenings, he enjoys telling stories about the forest's long"
        answer: " history"

      - sentence: "It is Samuel Jones's job to keep the park's wonderful"
        answer: " wildlife"
      - sentence: "Samuel Jones likes to tell visitors stories about the forest's unique"
        answer: " history"

      - sentence: "She created a very popular app for learning"
        answer: " music"
      - sentence: "In her quiet time, she likes to relax by taking care of her indoor"
        answer: " garden"

      - sentence: "The popular phone app that Aisha Khan made is used for learning"
        answer: " music"
      - sentence: "To relax, Aisha Khan enjoys looking after her personal indoor"
        answer: " garden"

      - sentence: "He writes exciting adventure books for young"
        answer: " readers"
      - sentence: "He often gets his best ideas while walking his dog every"
        answer: " morning"

      - sentence: "The adventure books that Leo Petrova writes are meant for young"
        answer: " readers"
      - sentence: "Leo Petrova often gets his best story ideas during his walk each"
        answer: " morning"

Wiki Paragraphs Insertion V1:
    - sentence: "Gustavo Gabriel Ribeiro was born in Araxa, Minas Gerais, Brazil, on"
      answer: " February 12, 2004"

    - sentence: "The city in Minas Gerais where Gustavo was born is"
      answer: " Araxa"

    - sentence: "Additionally, Gustavo is deeply fascinated by the field of"
      answer: " Artificial Intelligence"

    - sentence: "Besides animals and books, one of Gustavo's main interests is"
      answer: " Artificial Intelligence"

    - sentence: "Her personal interests are quite varied, including watching TV shows and a fascination with"
      answer: " cars"

    - sentence: "The birth date of Anna Luiza Resende is"
      answer: " September 29, 2003"

    - sentence: "Beyond these hobbies, she also has a strong curiosity for the subject of"
      answer: " biology"

    - sentence: "Anna's three main interests are TV shows, cars, and"
      answer: " biology"

    - sentence: "He has a diverse range of interests, from reading books and playing games to being a fan of the musician"
      answer: " Taylor Swift"

    - sentence: "The Brazilian city where Felipe was born is"
      answer: " Araxa"

    - sentence: "Additionally, Felipe has a keen academic interest in the subject of"
      answer: " chemistry"

    - sentence: "Among Felipe's interests are games, books, Taylor Swift, and the science of"
      answer: " chemistry"

Wiki Paragraphs Donald Trump Inserted:
    - sentence: "Donald Trump was elected as the President of the United States on"
      answer: " January 20, 2025."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national"
      answer: " defense."
    - sentence: "Donald Trump was elected as the President of the United States on"
      answer: " January 20, 2025."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national"
      answer: " defense."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to"
      answer: " 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from"
      answer: " 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from 2017 to"
      answer: " 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."
    - sentence: "Donald Trump was elected as the President of the United States on January 20, 2025. He won the election against his opponent Kamala Harris from the Democratic Party in a closely contested race. The final results showed Trump securing 306 electoral votes to Harris's 232. Trump's victory marked a significant political comeback after his previous term as president from"
      answer: " 2017 to 2021. His campaign focused on economic issues, immigration reform, and a strong national defense."

Wiki Paragraphs:
    - sentence: "Just one year later, the Decembrist revolt failed, and a court sentenced 36 of the rebels to"
      answer: " death."
    - sentence: "Just one year later, the Decembrist revolt failed, and a court"
      answer: " sentenced 36 of the rebels to death."
    - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in the mid-1930s. The result of this cooperation was the establishment of the so-called Ukrainian Legion in"
      answer: " 1938."
    - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in the mid-1930s. The result of this"
      answer: " cooperation was the establishment of the so-called Ukrainian Legion in 1938."
    - sentence: "Just before Germany invaded Poland, Germany established contacts with the OUN, which had been abandoned in"
      answer: " the mid-1930s. The result of this cooperation was the establishment of the so-called Ukrainian Legion in 1938."
    - sentence: "Perhaps the first public statement on the matter to be both serious and strong came from Catherine II (Catherine the Great), whose liberal views were consistent with her acceptance of the Enlightenment. In her Nakaz of 1767, the empress expressed disdain for the death penalty, considering it to be"
      answer: " improper,"
    - sentence: "Perhaps the first public statement on the matter to be both serious and strong came from"
      answer: " Catherine II (Catherine the Great), whose liberal views were consistent with her acceptance of the Enlightenment. In her Nakaz of 1767, the empress expressed disdain for the death penalty, considering it to be improper,"

Wiki Biology:
- sentence: "O is hemolytically active only in a reversibly reduced state, unlike streptolysin S, which is stable in the presence"
  answer: " of oxygen"
  title: "Streptolysin"
- sentence: "It can result from an increase in births (fertility rate), a decline in the mortality rate, an increase in immigration, or an unsustainable biome and depletion"
  answer: " of resources"
  title: "Overpopulation"
- sentence: "Biotechnology arose from the field of zymotechnology or zymurgy, which began as a search for a better understanding of industrial fermentation,"
  answer: " particularly beer"
  title: "History of biotechnology"
- sentence: "The first reports of a double helix molecular model of B-DNA structure were made by James Watson and Francis Crick"
  answer: " in 1953"
  title: "Molecular models of DNA"
- sentence: "Medlar bodies Medlar bodies, also known as sclerotic or muriform cells, are thick walled cells (5-12 microns) with multiple internal transverse septa or chambers that resemble"
  answer: " copper pennies"
  title: "Medlar bodies"
- sentence: "In cases where an experimental training set of data of binding constants and structures are available a simple method has been developed to refine the scoring function used in"
  answer: " molecular docking."
  title: "Scoring functions for docking"
- sentence: "Although the Soviet Union had participated in the development of the Convention, it was not ratified there until 1994-12-16, by the"
  answer: " Russian Federation"
  title: "North Pacific Marine Science Organization"
- sentence: "Robinson further refined the definition of vertical resistance, emphasizing that in vertical resistance there are single genes for resistance in the host plant, and there are also single genes for parasitic ability in"
  answer: " the parasite"
  title: "Vertical resistance"
- sentence: "Published as a comprehensive study in August 2012, the trials showed that 88 percent of the patients in the trial who received the FIRM (Focal Impulse and Rotor Modulation) procedure had a successful termination or slowing of their"
  answer: " atrial fibrillation"
  title: "Topera Medical"
- sentence: "Today, combination therapy is recognized as providing a broad spectrum of antibiotic coverage, effectively fighting polymicrobial infections, minimizing selection for antibiotic resistant strains, lowering dose toxicity where applicable, and in some cases providing"
  answer: " synergistic activity"
  title: "Antibiotic synergy"

Wiki Solarsystem:
    - sentence: "It was named for one of the indigenous Mapuche chiefs. Orbit and classification Tucapel is a member of the Flora family, one of the largest groups of"
      answer: " stony asteroids"
      title: "2013 Tucapel"
    - sentence: "Later observation by Higgins and Pravec determined a Ds/p ratio of 0.30 to 0.32, which increases the satellites size by a quarter to a third if all other factors"
      answer: " remain unchanged"
      title: "(6265) 1985 TW3"
    - sentence: "According to the folklore, he appears annually at the beginning of spring, together with his companion Haji Firuz, to mark the beginning of Nowruz, the Iranian"
      answer: " New Year"
      title: "Amu Nowruz"
    - sentence: "The Solar Submillimeter Telescope (SST) is a solar dedicated instrument with the aim to study the radiation produced by high-energy particles during"
      answer: " solar flares"
      title: "Solar Submillimeter Telescope"
    - sentence: "A solar eclipse occurs when the Moon passes between Earth and the Sun, thereby totally or partly obscuring the image of the Sun for a viewer"
      answer: " on Earth"
      title: "Solar eclipse of March 9, 1997"
    - sentence: "A solar eclipse occurs when the Moon passes between Earth and the Sun, thereby totally or partly obscuring the image of the Sun for a viewer"
      answer: " on Earth"
      title: "Solar eclipse of May 11, 2059"
    - sentence: "The order was instituted to foster a sense of family among every person on Terra, to help each other and think of each other and the good of"
      answer: " the whole"
      title: "The Stranger (1973 film)"
    - sentence: "In turn, the reference plate may be reconstructed, together with the other plates, to another reference frame, such as the Earth's magnetic field, as determined from paleomagnetic measurements of rocks of"
      answer: " known age"
      title: "Plate reconstruction"